export const tbodyData = orders.map(order => ({
    'SESS_TMPL_ID': order.SESS_TMPL_ID,
    'TOTAL': order.TOTAL,
    'DELIVERY_CHARGE': order.DELIVERY_CHARGE,
    'DELIVERY_METHOD': order.DELIVERY_METHOD,
    'PAYMENT_METHOD': order.PAYMENT_METHOD,
    'CREATED': order.CREATED,
    'ENDED': order.ENDED,
    'SESSION': order.SESSION,
    'CUST_NAME': order.CUST_NAME,
    'ORDER_NUM': order.ORDER_NUM,
    'CITY': order.CITY,
    'STREET_ADDR': order.STREET_ADDR,
    'NOTES': order.NOTES,
    'STATUS': order.STATUS,
}));